# render.yaml - Optimized for Python 3.13
services:
  - type: web
    name: nifty50-analyzer
    env: python
    region: ohio
    plan: free
    buildCommand: "python -m pip install --upgrade pip && pip install --only-binary=all -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false